pipeline{
    agent any
    stages{
        stage('echo string'){
            steps{
                echo "Hello AAkash "
                echo "Hello AAdhrtyj "

            }
        }
        
        }
        
    }
